### ISSUE TITLE
Audio and Video features for MOSI

### ISSUE THREAD

**Issue by zsun227** [yaohungt/Multimodal-Transformer#4]
Hi, 

Thanks a lot for sharing your code and data. However, after checking the CMU-MOSI dataset (downloaded from https://www.dropbox.com/sh/hyzpgx1hp9nj37s/AAB7FhBqJOFDw2hEyvv2ZXHxa?dl=0) 
I found that each MOSI example's audio feature is only 5-dim instead of 74 while the video is only 20-dim instead of 35...However, MOSEI and IEMOCAP have correct audio and video data. 

So could you double-check the MOSI dataset? Or you indeed used that shorter audio/video feature?

Thanks!

**Comment by yaohungt** [comment]
Hi, 

For more details about the feature preprocessing, you may contact pliang@cs.cmu.edu who is in charge of it. To the best of my knowledge, these features are selected after feature selection. 

I tried both the unselected/ post-selected features, it turned out that they worked the same. To remain consistency with prior work, the experiments use the post-selected features.
